package com.metsci.laproc.display;

import com.jogamp.opengl.util.FPSAnimator;
import com.metsci.glimpse.canvas.NewtSwingGlimpseCanvas;
import com.metsci.glimpse.docking.View;
import com.metsci.laproc.plotting.Graph;
import com.metsci.laproc.plotting.GraphableData;

import javax.swing.*;
import java.util.Observable;
import java.util.Observer;

/**
 * Created by porterjc on 9/26/2016.
 */
public class GraphPanel implements ITool, Observer{
    private NewtSwingGlimpseCanvas canvas;
    private GraphDisplayer graphDisplayer;
    private Graph graph;

    /**
     * Simple constructor
     * Creaded by porterjc on 9/22/2016
     */
    public GraphPanel(Graph graph){
        this.graph = graph;
        canvas = new NewtSwingGlimpseCanvas();
        new FPSAnimator(canvas.getGLDrawable(), 120).start();
        GraphDisplayer dis = new GraphDisplayer(this.graph);
        this.addGraphToCanvas(dis);
    }

	/**
     * Takes a graph and properly builds a canvas from the layout generated by the graph
     * Creaded by porterjc on 9/22/2016
     */
    public void addGraphToCanvas(GraphDisplayer displayer) {
        canvas.removeAllLayouts();
        canvas.addLayout(displayer.getLayout());
        this.graphDisplayer = displayer;
    }

    /**
     * Returns the canvas
     * Creaded by porterjc on 9/22/2016
     */
    public NewtSwingGlimpseCanvas getCanvas(){
        return canvas;
    }

    public View getView() {
        return new View("Graph", this.getCanvas(), "Graph", true);
    }

    public void update(Observable o, Object arg) {

    }

    /**
     * Updates the displayed graph
     */
    public void updateGraph() {
        canvas.removeAllLayouts();
        canvas.addLayout(graphDisplayer.getLayout());
    }
}
