package com.metsci.laproc.display;

import com.jogamp.opengl.util.FPSAnimator;
import com.metsci.glimpse.canvas.NewtSwingGlimpseCanvas;
import com.metsci.glimpse.docking.View;
import com.metsci.laproc.application.DataReference;
import com.metsci.laproc.plotting.GraphPoint;
import com.metsci.laproc.utils.IActionReceiver;
import com.metsci.laproc.utils.IObserver;


/**
 * Created by porterjc on 9/26/2016.
 */
public class GraphPanel implements ITool, IObserver<DataReference> {
    private NewtSwingGlimpseCanvas canvas;
    private GraphDisplayer graphDisplayer;

    /**
     * Simple constructor
     * Creaded by porterjc on 9/22/2016
     */

    public GraphPanel(DataReference reference, IActionReceiver<GraphPoint[]>... actionReceivers){
        reference.addObserver(this);
        canvas = new NewtSwingGlimpseCanvas();
        new FPSAnimator(canvas.getGLDrawable(), 120).start();
        graphDisplayer = new GraphDisplayer(reference, actionReceivers);
        this.addGraphToCanvas(graphDisplayer);
    }

	/**
     * Takes a graph and properly builds a canvas from the layout generated by the graph
     * Creaded by porterjc on 9/22/2016
     */
    public void addGraphToCanvas(GraphDisplayer displayer) {
        canvas.removeAllLayouts();
        canvas.addLayout(displayer.getLayout());
        this.graphDisplayer = displayer;
    }

    /**
     * Returns the canvas
     * Creaded by porterjc on 9/22/2016
     */
    public NewtSwingGlimpseCanvas getCanvas(){
        return canvas;
    }

    public View getView() {
        return new View("Graph", this.getCanvas(), "Graph", true);
    }

    public int getDefaultPosition() {
        return ITool.CENTERPOSITION;
    }

    public void update(DataReference reference) {
        canvas.removeAllLayouts();
        canvas.addLayout(graphDisplayer.getLayout());
    }
}
