package com.metsci.laproc.tools;

import com.jogamp.opengl.util.FPSAnimator;
import com.metsci.glimpse.canvas.NewtSwingGlimpseCanvas;
import com.metsci.glimpse.docking.View;
import com.metsci.glimpse.plot.Plot2D;
import com.metsci.laproc.datareference.GraphReference;
import com.metsci.laproc.plotting.Graph;
import com.metsci.laproc.uicomponents.GraphDisplayer;
import com.metsci.laproc.plotting.GraphPoint;
import com.metsci.laproc.utils.IAction;
import com.metsci.laproc.utils.IObserver;


/**
 * Created by porterjc on 9/26/2016.
 */
public class GraphPanel implements ITool, IObserver<GraphReference> {
    private NewtSwingGlimpseCanvas canvas;
    private GraphDisplayManager graphDisplayManager;
    private GraphDisplayer graphDisplayer;

    /**
     * Simple constructor
     * Creaded by porterjc on 9/22/2016
     */

    public GraphPanel(GraphReference reference, GraphDisplayManager manager, IAction<GraphPoint[]>... clickActions){
        reference.addObserver(this);
        canvas = new NewtSwingGlimpseCanvas();
        new FPSAnimator(canvas.getGLDrawable(), 120).start();
        graphDisplayManager = manager;
        graphDisplayer = new GraphDisplayer(clickActions);
        this.addGraphToCanvas(graphDisplayer);
    }

	/**
     * Takes a graph and properly builds a canvas from the layout generated by the graph
     * Creaded by porterjc on 9/22/2016
     */
    public void addGraphToCanvas(GraphDisplayer displayer) {
        canvas.removeAllLayouts();
        Plot2D plot = displayer.getLayout();
        canvas.addLayout(plot);
        this.graphDisplayer = displayer;
    }

    /**
     * Returns the canvas
     * Creaded by porterjc on 9/22/2016
     */
    public NewtSwingGlimpseCanvas getCanvas(){
        return canvas;
    }

    public View getView() {
        return new View("Graph", this.getCanvas(), "Graph", true);
    }

    public int getDefaultPosition() {
        return ITool.CENTERPOSITION;
    }

    public void update(GraphReference reference) {
        canvas.removeAllLayouts();
        Graph graph = reference.getGraph();
        graphDisplayer.setGraph(reference.getGraph());
        Plot2D plot2D = graphDisplayer.getLayout();
        graphDisplayManager.updateGraph(graph, plot2D);
        canvas.addLayout(plot2D);
    }
}
